name: Compile FVS

on:
  push:
    branches: [ "main", "bc_sourcelist", "debug-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        #fvs_variant: [ak,bc,bm,ca,ci,cr,cs,ec,em,ie,kt,ls,nc,ne,oc,on,op,pn,sn,so,tt,ut,wc,ws]
        fvs_variant: [ak,bm,ca,ci,cr,cs,ec,em,ie,kt,ls,nc,ne,oc,op,pn,sn,so,tt,ut,wc,ws]
        #fvs_variant: [pn,wc]
      
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout FVS
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Install MSYS2
      if: runner.os == 'Windows'
      # https://github.com/msys2/setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        install: |
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-gcc-fortran
        
    - name: Compile
      working-directory: ./bin
      run: |
        make FVS${{ matrix.fvs_variant }}${{ runner.os == 'Windows' && '.exe' || '' }}
        make FVS${{ matrix.fvs_variant }}${{ runner.os == 'Windows' && '.dll' || '.so' }}

    - name: Test
      working-directory: ./tests
      run: make FVS${{ matrix.fvs_variant }}

    - name: Set Env Vars
      id: vars
      shell: bash
      run: |
        short_sha=$(git rev-parse --short "$GITHUB_SHA")
        echo "SHORT_SHA=$short_sha" >> "$GITHUB_ENV"
        branchName=$(echo "$GITHUB_REF" | sed 's/refs\/heads\///')
        echo "BRANCH=$branchName" >> "$GITHUB_ENV"
        osName=$(echo "${{ matrix.os }}" | sed 's/-latest//')
        echo "OS_NAME=$osName" >> "$GITHUB_ENV"
        
    - name: Archive Binaries
      uses: actions/upload-artifact@v4
      with:
        name: fvs-${{ env.OS_NAME }}-${{ env.BRANCH }}-${{ env.SHORT_SHA }}
        path: |
          bin/FVS${{ matrix.fvs_variant }}${{ runner.os == 'Windows' && '.exe' || '' }}
          bin/FVS${{ matrix.fvs_variant }}${{ runner.os == 'Windows' && '.dll' || '.so' }}
